name: Build and Package

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout the repository
        uses: actions/checkout@v4

      # 拉取子模块
      - name: Pull submodules
        run: git submodule update --init -- 'arknights-mower'

      # 创建虚拟环境并安装依赖
      - name: Setup Python environment and install dependencies
        run: |
          cd arknights-mower
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 压缩整个 test_work_flow 目录为 zip
      - name: Compress test_work_flow directory to zip
        run: |
          zip -r test_work_flow.zip test_work_flow/
        
      # 上传 zip 文件作为构建产物
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: test_work_flow-zip
          path: test_work_flow.zip
