name: Build and Package

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout the repository
        uses: actions/checkout@v4

      # 拉取子模块
      - name: Pull submodules
        run: git submodule update --init --recursive

      # 创建虚拟环境并安装依赖
      - name: Setup Python environment and install dependencies
        run: |
          cd mower-ng
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 压缩整个 program 目录为 zip
      - name: Compress program directory to zip
        run: |
          zip -r program.zip program/
        
      # 上传 zip 文件作为构建产物
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: program-zip
          path: program.zip
